### PR TITLE
Allow swagger definition to be an object + barrel file optional now

### PR DESCRIPTION
**Pull request by rbsloot**

### CODE REVIEW

**Comment by areijngoudt** [comment]
Why swaggerInput instead of swaggerFileName? Its still the fileName right? If so, I want to keep the original name of the argument

**Comment by rbsloot** [comment]
It can be either a filename or a swagger object now

**Comment by areijngoudt** [comment]
I see. I propose another solution though. Please provide either the swaggerFileName or the swaggerFile as on object

**Comment by rbsloot** [comment]
The `swaggerInput` is either a string with the filename to a <swagger>.json which provides a swagger object. Or `swaggerInput` is the swagger object itself right from the start. This is what you mean right?

Something like this:
```typescript
export function generateTSFiles(swaggerInput: string | Swagger, options: GeneratorOptions) {
```

**Comment by areijngoudt** [comment]
No, I mean provide 2 separate arguments called `swaggerFileName: string` and `swagger: Swagger`.
One of these should be filled in

**Comment by rbsloot** [comment]
Ah alright, I can implement it like that. It would mean that there is no backwards compatibility anymore, because everyone will have to either set undefined on the first or the second argument.

If you are okay with this I will change the code.

**Pull request merged**
